### ISSUE TITLE
[Feature Request] Expanded Invisibility

### ISSUE THREAD

**Issue by ProfessionalBoatDrifter** [NewAmazingPVP/BetterInvisibility#4]
I have some ideas I think could work well within the BetterInvisibility scope.

- Allow us to define different invisibility tiers with per-tier settings that depend on the potion strength.
- Allow Night Vision to counter Invisibility.

I've been looking for a plugin that improves the invis effect and yours seems to be the best one around. So I hope you'll consider this! :)

Example config:
```
hide:
  invisibility_1: # Name can be anything
    potion_effect: INVISIBILITY # Uses: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html -Either "INVISIBILITY" or "NIGHT_VISION"
    level: 0 # Potion strength, '0' being Invisibility I
    helment: false
    chestplate: false
    leggings: false
    boots: false
    mainhand: false
    offhand: false
    potionParticles: true

  invisibility_2:
    potion_effect: INVISIBILITY
    level: 1
    helment: true
    chestplate: true
    leggings: true
    boots: true
    mainhand: false
    offhand: false
    potionParticles: true


reveal: # New
  night_vision_1: # Again, any name
    potion_effect: NIGHT_VISION
    level: 0 # Potion strength
    radius: 5 # Radius in blocks which reveal Invisibility X players. Set to -1 for any range
    effective: 0 # Only reveals Invisibility I or lower. Set to -1 to not reveal any

  night_vision_2: # Again, any name
    potion_effect: NIGHT_VISION
    level: 0 # Potion strength
    radius: 7 # Radius in blocks which reveal Invisibility X players. Set to -1 for any range
    effective: 1 # Reveals Invisibility II or lower

enable_workaround: false
```
